export const SET_EQUIPMENT = 'SET_EQUIPMENT';
export const SET_SUB_MUSCLES = 'SET_SUB_MUSCLES';
export const SET_MUSCLE_GROUP = 'SET_MUSCLE_GROUP';
export const SET_INCLUDE_NO_EQUIPMENT = 'SET_INCLUDE_NO_EQUIPMENT';
export const GET_EQUIPMENT_OPTIONS = 'GET_EQUIPMENT_OPTIONS';
export const SET_SELECTIONS_LOADING = 'SET_SELECTIONS_LOADING';
export const SELECTIONS_ERROR = 'SELECTIONS_ERROR';

export const GET_WORKOUTS = 'GET_WORKOUTS';
export const CLEAR_WORKOUTS = 'CLEAR_WORKOUTS';
export const WORKOUTS_ERROR = 'WORKOUT_ERROR';
export const SET_WORKOUTS_LOADING = 'SET_WORKOUTS_LOADING';
