export const SET_EQUIPMENT = 'SET_EQUIPMENT';
export const SET_SUB_MUSCLES = 'SET_SUB_MUSCLES';
export const SET_MUSCLE_GROUP = 'SET_MUSCLE_GROUP';
export const SET_INCLUDE_NO_EQUIPMENT = 'SET_INCLUDE_NO_EQUIPMENT';
export const WORKOUT_ERROR = 'WORKOUT_ERROR';
export const SET_LOADING = 'SET_LOADING';
