export const SET_EQUIPMENT = 'SET_EQUIPMENT';
export const SET_SUB_MUSCLES = 'SET_SUB_MUSCLES';
export const SET_MUSCLE_GROUP = 'SET_MUSCLE_GROUP';
export const GET_EQUIPMENT_OPTIONS = 'GET_EQUIPMENT_OPTIONS';
export const SET_SELECTIONS_LOADING = 'SET_SELECTIONS_LOADING';
export const SELECTIONS_ERROR = 'SELECTIONS_ERROR';

export const GET_WORKOUTS = 'GET_WORKOUTS';
export const CLEAR_WORKOUTS = 'CLEAR_WORKOUTS';
export const SHUFFLE_WORKOUTS = 'SHUFFLE_WORKOUTS';
export const WORKOUTS_ERROR = 'WORKOUT_ERROR';
export const SET_WORKOUTS_LOADING = 'SET_WORKOUTS_LOADING';

export const SET_CURR_USER = 'SET_CURR_USER';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_MESSAGE = 'SET_MESSAGE';
export const USERS_ERROR = 'USERS_ERROR';

export const SET_PLAN_ID = 'SET_PLAN_ID';
export const SET_PLAN_NAME = 'SET_PLAN_NAME';
export const SET_PLAN_STEPS = 'SET_PLAN_STEPS';
export const ADD_PLAN_STEP = 'ADD_PLAN_STEP';
export const GET_CURR_USER_PLANS = 'GET_CURR_USER_PLANS';
export const DELETE_CURR_USER_PLAN = 'DELETE_CURR_USER_PLAN';
export const PLANS_ERROR = 'PLANS_ERROR';
